### PR TITLE
Create data-ghoti.yml

### PR DESCRIPTION
**Pull request by data-ghoti**

### CODE REVIEW

**Comment by afewell** [comment]
@data-ghoti I am not sure why this workflow failed, the workflow itself has been working alright so I am not sure if it was just a random processing error or if there may be a bug, but in any case I manually updated the record ... I just manually provisioned your badge so you should get an email from badgr, I will update your member page record as soon as I get the chance and will leave this open until I get it updated. Thanks!

**Comment by afewell** [comment]
Hi @data-ghoti I am so sorry I forgot about this and dropped the ball! If I remember correctly, I think I manually assigned you this badge, but I can't remember for sure. 

Could you please let me know if I got this badge assigned to you already or if I forgot? If I forgot, I will manually issue the badge, so sorry again for dropping the ball!

I am going to keep this request open to track this, and close your other open requests since we can use this one for tracking. Please feel free to respond here and I will keep an eye on this, but my github inbox is extremely overwhelmed so also feel free to dm me on linkedin, twitter, or email afewell@vmware.com if I dont respond promptly. 

Thanks!

**Comment by afewell** [comment]
Hi @data-ghoti I was able to confirm I did manually assign this badge to you back in July so hopefully you received that record! While the badgr.com site is usually the best place (most authoritative source) to keep and verify your badge completion record, I have also updated your member page so it properly reflects your certificate award. 

Since that is all fixed now I am going to close this ticket. 

Thanks so much!

**Comment by data-ghoti** [comment]
Thank you Arthur!

--dg

**Pull request closed without merging**
